@startuml Cas d'utilisation
'https://plantuml.com/use-case-diagram

left to right direction

title Diagramme de cas d'utilisation

'' ACTORS ''
actor Administrateur as a
actor Utilisateur as u
actor Visiteur as g
a -|> u
u -|> g

'' PACKAGES ''
package leomoilledotcom {
    '' MANAGE ''
    usecase postComment as "Publier\n un commentaire"
    usecase deleteOwnComment as "Supprimer\n son commentaire"
    usecase deleteComment as "Supprimer\n un commentaire"
    usecase editComment as "Éditer\n un commentaire"
    usecase approveComment as "Approuver\n un commentaire"
    usecase deleteUser as "Supprimer\n un utilisateur"
    usecase editOwnComment as "Éditer\n son commentaire"
    usecase deletePost as "Supprimer\n un article"
    usecase editPost as "Éditer\n un article"
    usecase addPost as "Ajouter\n un article"
    usecase readPost as "Lire\n un article"
    usecase login as "Se connecter"
    usecase signup as "S'inscrire"
    usecase logout as "Se déconnecter"
    usecase listPosts as "Lister les articles"
    usecase sendContact as "Envoyer un message via\n un formulaire de contact"
    ' Ajouter toutes les actions manquantes'
}

'' RELATIONS ''


'' DISPLAYS ''
'' Guest
g --[#blue] login
g --[#blue] listPosts
g --[#blue] signup
g --[#blue] readPost
g --[#blue] sendContact


'' User
u --[#green] postComment
u --[#green] editOwnComment
u --[#green] deleteOwnComment
u --[#green] logout

'' Admin
a -- addPost
a -- editPost
a -- deletePost
a -- editComment
a -- deleteComment
a -- approveComment
a -- deleteUser

'' NOTES ''


@enduml
